[tool.black]
line-length = 100
skip-string-normalization = true
exclude = "(\.venv|build|dist|node_modules|frontend)/"

[tool.isort]
profile = "black"
line_length = 100
skip_gitignore = true
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.ruff]
line-length = 100
exclude = [".venv", "build", "dist", "node_modules", "frontend"]
select = ["E", "F", "W", "I", "N", "UP"]
ignore = ["E203", "W503"]

[tool.flake8]
max-line-length = 100
extend-ignore = E203,W503 