global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API网关监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # 几何服务监控
  - job_name: 'geometry-service'
    static_configs:
      - targets: ['geometry-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # 网格服务监控
  - job_name: 'mesh-service'
    static_configs:
      - targets: ['mesh-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # 分析服务监控
  - job_name: 'analysis-service'
    static_configs:
      - targets: ['analysis-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # 结果服务监控
  - job_name: 'result-service'
    static_configs:
      - targets: ['result-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # 项目服务监控
  - job_name: 'project-service'
    static_configs:
      - targets: ['project-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # 文件服务监控
  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:8006']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # 通知服务监控
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8007']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # RabbitMQ监控
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s

  # MinIO监控
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  # Consul监控
  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']
    metrics_path: '/v1/agent/metrics'
    params:
      format: ['prometheus']
    scrape_interval: 30s

  # 通过Consul服务发现自动监控
  - job_name: 'consul-services'
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__meta_consul_service_address]
        target_label: __address__
      - source_labels: [__meta_consul_service_port]
        target_label: __address__
        regex: (.*)
        replacement: ${1}:${__meta_consul_service_port} 